name: Flask CI/CD - Local Machine

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: windows-latest  # GitHub-hosted Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          python.exe -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt
        shell: pwsh

      - name: Create ZIP for Deployment
        run: |
          Compress-Archive -Path * -DestinationPath project.zip -Force
        shell: pwsh

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-zip
          path: project.zip

  deploy:
    needs: build
    runs-on: windows-latest  # Still on GitHub-hosted Windows runner

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-zip
          path: C:\Users\vivek\Downloads  # Change this to your local path

      - name: Transfer ZIP to Local PC
        run: |
         $LOCAL_PC_IP = "106.51.200.6"  # Replace with your local PC's IP
         $LOCAL_USER = "vivek"  # Replace with your Windows username
         $ZIP_PATH = "C:\Users\vivek\Downloads\project.zip"
         $DEST_PATH = "\\$LOCAL_PC_IP\C$\Users\$LOCAL_USER\Downloads\project.zip"

         Copy-Item -Path $ZIP_PATH -Destination $DEST_PATH -ToSession (New-PSSession -ComputerName $LOCAL_PC_IP -Credential (Get-Credential)) -Force
        shell: pwsh

      - name: Extract & Start Flask App
        run: |
          $DEPLOY_PATH = "C:\Users\vivek\source\repos\githubDeployed"

          # Ensure directory exists
          if (-Not (Test-Path $DEPLOY_PATH)) { New-Item -ItemType Directory -Path $DEPLOY_PATH -Force | Out-Null }

          Expand-Archive -Path "C:\Users\vivek\Downloads\project.zip" -DestinationPath $DEPLOY_PATH -Force

          # Activate Virtual Environment & Start Flask
          cd $DEPLOY_PATH
          python -m venv venv
          venv\Scripts\activate
          python.exe -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r backend/requirements.txt
          python app.py
        shell: pwsh
