name: Flask CI/CD Pipeline - Localhost

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build:
    runs-on: windows-latest  # Running on Windows

    steps:
      - name: Checkout Repository (Pull latest code)
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          python.exe -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # - name: Run Tests
      #   run: |
      #     venv\Scripts\activate
      #     pytest

      - name: Create ZIP for Deployment (Local Machine)
        run: |
          $PROJECT_NAME = "ParivarSearch"
          $ZIP_NAME = "$PROJECT_NAME.zip"
          $LOCAL_PATH = "C:\Users\vivek\source\repos\githubProjects"

          if (-Not (Test-Path $LOCAL_PATH)) { New-Item -ItemType Directory -Path $LOCAL_PATH }

          Compress-Archive -Path * -DestinationPath "$LOCAL_PATH\$ZIP_NAME" -Force

          echo "ZIP_NAME=$ZIP_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Deploy Locally from ZIP
        run: |
          echo "Starting local deployment on Windows..."

          $LOCAL_PATH = "C:\Users\vivek\source\repos\githubProjects"
          $DEPLOY_PATH = "C:\Users\vivek\source\repos\githubDeployed"
          $LATEST_ZIP = Get-ChildItem -Path $LOCAL_PATH -Filter "ParivarSearch.zip" | Sort-Object LastWriteTime -Descending | Select-Object -First 1

          echo "Deploying from: $LOCAL_PATH\$LATEST_ZIP"
          echo "Extracting to: $DEPLOY_PATH"

          if (-Not (Test-Path $DEPLOY_PATH)) { New-Item -ItemType Directory -Path $DEPLOY_PATH }

          Expand-Archive -Path "$LOCAL_PATH\$LATEST_ZIP" -DestinationPath $DEPLOY_PATH -Force

          echo "✅ Deployment completed successfully."

      - name: Run Flask App
        run: |
          cd C:\Users\vivek\source\repos\githubDeployed\ParivarSearch
          python -m venv venv
          venv\Scripts\activate
          pip install --no-cache-dir -r requirements.txt
          python app.py
