name: Deploy Flask App with ngrok (Windows)

on:
  workflow_run:
    workflows: ["Deploy Vite App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Uses a self-hosted runner (Windows)

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🚀 Start ngrok
        run: |
          & "C:\ngrok\ngrok.exe" http 5173
        shell: powershell

      - name: 🔄 Start ngrok
        run: |
          Start-Process -NoNewWindow -FilePath "C:\ngrok\ngrok.exe" -ArgumentList "http 5173"
        shell: powershell

      - name: 🔍 Debug ngrok tunnel
        run: Invoke-RestMethod http://localhost:4040/api/tunnels | ConvertTo-Json -Depth 3
        shell: powershell

      - name: 🔗 Get Ngrok URL for Port 5173
        run: |
          $ngrokUrl = (Invoke-RestMethod http://localhost:4040/api/tunnels).tunnels | Where-Object { $_.config.addr -eq "http://localhost:5173" } | Select-Object -ExpandProperty public_url
          echo "URL=$ngrokUrl" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: powershell

      - name: Print the Public URL
        run: echo "Ngrok URL is $env:URL"
        shell: powershell

      - name: ✅ Test API Endpoint by PORT
        run: Invoke-WebRequest -Uri "http://localhost:5173" -UseBasicParsing
        shell: powershell

      - name: ✅ Test API Endpoint by Ngrok URL
        run: Invoke-WebRequest -Uri "$env:URL" -UseBasicParsing
        shell: powershell
