name: Deploy Vite App

on:
  workflow_run:
    workflows: ["Deploy Flask App"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted  # Uses a self-hosted runner (Windows)

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📦 Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 📦 Install Node.js & npm Dependencies
        run: |
          npm install
          npm run build  # Build frontend
        shell: powershell

      - name: 🔥 Start Frontend (Vite on Port 5173)
        run: |
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run dev -- --host"
        shell: powershell

      - name: 📡 Trigger Ngrok Workflow
        run: |
          gh workflow run ngrok.yml
        env:
          GH_TOKEN: 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
        shell: bash
